### ISSUE TITLE
issue with DIRKstep_basic()

### ISSUE THREAD

**Issue by schlanghorvetz** [drreynolds/rklab#2]
Hey. I believe there is an issue when running the DIRK solver and I don't know if it has been noticed. The error message is

**Output argument "y" (and possibly others) not assigned a value in the execution with
"solve_DIRK>DIRKstep_basic" function.

Error in solve_DIRK (line 127)
         [Ynew,cfail,lin] = DIRKstep_basic(fcn, Jfcn, Y0, t, h, B);

Error in testnm (line 32)
[tvals,Y,nsteps,lits,h] = solve_DIRK(fcn,Jfcn,tvals,Y0,B,rtol,atol,hmin,hmax,hinit);**

**Comment by drreynolds** [comment]
Thanks for letting me know.  I'm on vacation this week, and conference travel next week, but will try to look into this soon.

**Comment by drreynolds** [comment]
I just pushed up a "fix" for this; however, the underlying problem in your case was not with the `solve_DIRK` function, but with the inputs that you provided to it from your `testnm` file.  Essentially, the `DIRKstep_basic` function was returning due to a failure in the Newton nonlinear solver; but when it tried to return it had not yet specified the output `y`.  

When the Newton nonlinear solver fails, it is almost always due to errors in the Jacobian function that was provided.  I recommend that you look at your `Jfcn` that you provided to `solve_DIRK` to check whether it correctly encodes the full set of partial derivatives for your `fcn` function.

Alternately, since this called `DIRKstep_basic` that means you were running with fixed time step sizes (i.e., not adaptive).  In that case, the Newton solver can also fail because your problem is highly nonlinear and you are asking it to take too large of a time step.
